# Generated by Django 5.1 on 2024-09-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameOfAllah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('transliteration', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
    ]
