# Generated by Django 5.1 on 2024-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names99', '0003_nameofallah_read_alter_nameofallah_meaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameofallah',
            name='full_meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nameofallah',
            name='meaning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nameofallah',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
