from django.core.management.base import BaseCommand
from reminders.models import NameOfAllah

class Command(BaseCommand):
    help = 'Populates the database with the 99 Names of Allah'

    def handle(self, *args, **kwargs):
        names = [
            {"day_number": 1, "name": "ٱلله", "transliteration": "Allah", "meaning": "The God"},
            {"day_number": 2, "name": "ٱلْرَّحْمَـانُ", "transliteration": "Ar-Rahmaan", "meaning": "The Most or Entirely Merciful"},
            {"day_number": 3, "name": "ٱلْرَّحِيْمُ", "transliteration": "Ar-Raheem", "meaning": "The Bestower of Mercy"},
            {"day_number": 4, "name": "ٱلْمَلِكُ", "transliteration": "Al-Malik", "meaning": "The King and Owner of Dominion"},
            {"day_number": 5, "name": "ٱلْقُدُّوسُ", "transliteration": "Al-Quddus", "meaning": "The Absolutely Pure"},
            {"day_number": 6, "name": "ٱلْسَّلَامُ", "transliteration": "As-Salam", "meaning": "The Perfection and Giver of Peace"},
            {"day_number": 7, "name": "ٱلْمُؤْمِنُ", "transliteration": "Al-Mu’min", "meaning": "The One Who gives Emaan and Security"},
            {"day_number": 8, "name": "ٱلْمُهَيْمِنُ", "transliteration": "Al-Muhaymin", "meaning": "The Guardian, The Witness, The Overseer"},
            {"day_number": 9, "name": "ٱلْعَزِيزُ", "transliteration": "Al-Azeez", "meaning": "The All Mighty"},
            {"day_number": 10, "name": "ٱلْجَبَّارُ", "transliteration": "Al-Jabbar", "meaning": "The Compeller, The Restorer"},
            {"day_number": 11, "name": "ٱلْمُتَكَبِّرُ", "transliteration": "Al-Mutakabbir", "meaning": "The Supreme, The Majestic"},
            {"day_number": 12, "name": "ٱلْخَالِقُ", "transliteration": "Al-Khaaliq", "meaning": "The Creator, The Maker"},
            {"day_number": 13, "name": "ٱلْبَارِئُ", "transliteration": "Al-Baari’", "meaning": "The Originator"},
            {"day_number": 14, "name": "ٱلْمُصَوِّرُ", "transliteration": "Al-Musawwir", "meaning": "The Fashioner"},
            {"day_number": 15, "name": "ٱلْغَفَّارُ", "transliteration": "Al-Ghaffar", "meaning": "The All- and Oft-Forgiving"},
            {"day_number": 16, "name": "ٱلْقَهَّارُ", "transliteration": "Al-Qahhar", "meaning": "The Subduer, The Ever-Dominating"},
            {"day_number": 17, "name": "ٱلْوَهَّابُ", "transliteration": "Al-Wahhaab", "meaning": "The Giver of Gifts"},
            {"day_number": 18, "name": "ٱلْرَّزَّاقُ", "transliteration": "Ar-Razzaaq", "meaning": "The Provider"},
            {"day_number": 19, "name": "ٱلْفَتَّاحُ", "transliteration": "Al-Fattah", "meaning": "The Opener, The Judge"},
            {"day_number": 20, "name": "ٱلْعَلِيمُ", "transliteration": "Al-‘Aleem", "meaning": "The All-Knowing, The Omniscient"},
            {"day_number": 21, "name": "ٱلْقَابِضُ", "transliteration": "Al-Qaabid", "meaning": "The Withholder"},
            {"day_number": 22, "name": "ٱلْبَاسِطُ", "transliteration": "Al-Baasit", "meaning": "The Extender"},
            {"day_number": 23, "name": "ٱلْخَافِضُ", "transliteration": "Al-Khaafidh", "meaning": "The Reducer, The Abaser"},
            {"day_number": 24, "name": "ٱلْرَّافِعُ", "transliteration": "Ar-Raafi’", "meaning": "The Exalter, The Elevator"},
            {"day_number": 25, "name": "ٱلْمُعِزُّ", "transliteration": "Al-Mu’izz", "meaning": "The Honourer, The Bestower"},
            {"day_number": 26, "name": "ٱلْمُذِلُّ", "transliteration": "Al-Muzil", "meaning": "The Dishonourer, The Humiliator"},
            {"day_number": 27, "name": "ٱلْسَّمِيعُ", "transliteration": "As-Samee’", "meaning": "The All-Hearing"},
            {"day_number": 28, "name": "ٱلْبَصِيرُ", "transliteration": "Al-Baseer", "meaning": "The All-Seeing"},
            {"day_number": 29, "name": "ٱلْحَكَمُ", "transliteration": "Al-Hakam", "meaning": "The Judge, The Giver of Justice"},
            {"day_number": 30, "name": "ٱلْعَدْلُ", "transliteration": "Al-‘Adl", "meaning": "The Utterly Just"},
            {"day_number": 31, "name": "ٱلْلَّطِيفُ", "transliteration": "Al-Lateef", "meaning": "The Subtle One, The Most Gentle"},
            {"day_number": 32, "name": "ٱلْخَبِيرُ", "transliteration": "Al-Khabeer", "meaning": "The Acquainted, the All-Aware"},
            {"day_number": 33, "name": "ٱلْحَلِيمُ", "transliteration": "Al-Haleem", "meaning": "The Most Forbearing"},
            {"day_number": 34, "name": "ٱلْعَظِيمُ", "transliteration": "Al-‘Atheem", "meaning": "The Magnificent, The Supreme"},
            {"day_number": 35, "name": "ٱلْغَفُورُ", "transliteration": "Al-Ghafoor", "meaning": "The Forgiving, The Exceedingly Forgiving"},
            {"day_number": 36, "name": "ٱلْشَّكُورُ", "transliteration": "Ash-Shakoor", "meaning": "The Most Appreciative"},
            {"day_number": 37, "name": "ٱلْعَلِيُّ", "transliteration": "Al-‘Aleem", "meaning": "The Most High, The Exalted"},
            {"day_number": 38, "name": "ٱلْكَبِيرُ", "transliteration": "Al-Kabeer", "meaning": "The Greatest, The Most Grand"},
            {"day_number": 39, "name": "ٱلْحَفِيظُ", "transliteration": "Al-Hafeedh", "meaning": "The Preserver, The All-Heedful and All-Protecting"},
            {"day_number": 40, "name": "ٱلْمُقِيتُ", "transliteration": "Al-Muqeet", "meaning": "The Sustainer"},
            {"day_number": 41, "name": "ٱلْحَسِيبُ", "transliteration": "Al-Haseeb", "meaning": "The Reckoner, The Sufficient"},
            {"day_number": 42, "name": "ٱلْجَلِيلُ", "transliteration": "Al-Jaleel", "meaning": "The Majestic"},
            {"day_number": 43, "name": "ٱلْكَرِيمُ", "transliteration": "Al-Kareem", "meaning": "The Most Generous, The Most Esteemed"},
            {"day_number": 44, "name": "ٱلْرَّقِيبُ", "transliteration": "Ar-Raqeeb", "meaning": "The Watchful"},
            {"day_number": 45, "name": "ٱلْوَاسِعُ", "transliteration": "Al-Waasi’", "meaning": "The All-Encompassing, the Boundless"},
            {"day_number": 46, "name": "ٱلْحَكِيمُ", "transliteration": "Al-Hakeem", "meaning": "The All-Wise"},
            {"day_number": 47, "name": "ٱلْوَدُودُ", "transliteration": "Al-Wadood", "meaning": "The Most Loving"},
            {"day_number": 48, "name": "ٱلْمَجِيدُ", "transliteration": "Al-Majeed", "meaning": "The Glorious, The Most Honorable"},
            {"day_number": 49, "name": "ٱلْبَاعِثُ", "transliteration": "Al-Ba’ith", "meaning": "The Resurrector, The Raiser of the Dead"},
            {"day_number": 50, "name": "ٱلشَّهِيدُ", "transliteration": "Ash-Shaheed", "meaning": "The All- and Ever Witnessing"},
            {"day_number": 51, "name": "ٱلْحَقُّ", "transliteration": "Al-Haqq", "meaning": "The Absolute Truth"},
            {"day_number": 52, "name": "ٱلْوَكِيلُ", "transliteration": "Al-Wakeel", "meaning": "The Trustee, The Disposer of Affairs"},
            {"day_number": 53, "name": "ٱلْقَوِيُّ", "transliteration": "Al-Qawiyy", "meaning": "The All-Strong"},
            {"day_number": 54, "name": "ٱلْمَتِينُ", "transliteration": "Al-Mateen", "meaning": "The Firm, The Steadfast"},
            {"day_number": 55, "name": "ٱلْوَلِيُّ", "transliteration": "Al-Waliyy", "meaning": "The Protecting Associate"},
            {"day_number": 56, "name": "ٱلْحَمِيدُ", "transliteration": "Al-Hameed", "meaning": "The Praiseworthy"},
            {"day_number": 57, "name": "ٱلْمُحْصِيُ", "transliteration": "Al-Muhsee", "meaning": "The All-Enumerating, The Counter"},
            {"day_number": 58, "name": "ٱلْمُبْدِئُ", "transliteration": "Al-Mubdi", "meaning": "The Originator, The Initiator"},
            {"day_number": 59, "name": "ٱلْمُعِيدُ", "transliteration": "Al-Mu’eed", "meaning": "The Restorer, The Reinstater"},
            {"day_number": 60, "name": "ٱلْمُحْيِى", "transliteration": "Al-Muhyee", "meaning": "The Giver of Life"},
            {"day_number": 61, "name": "ٱلْمُمِيتُ", "transliteration": "Al-Mumeet", "meaning": "The Bringer of Death, the Destroyer"},
            {"day_number": 62, "name": "ٱلْحَىُّ", "transliteration": "Al-Hayy", "meaning": "The Ever-Living"},
            {"day_number": 63, "name": "ٱلْقَيُّومُ", "transliteration": "Al-Qayoom", "meaning": "The Sustainer, The Self-Subsisting"},
            {"day_number": 64, "name": "ٱلْوَاجِدُ", "transliteration": "Al-Waajid", "meaning": "The Perceiver"},
            {"day_number": 65, "name": "ٱلْمَاجِدُ", "transliteration": "Al-Maajid", "meaning": "The Illustrious, the Magnificent"},
            {"day_number": 66, "name": "ٱلْوَاحِدُ", "transliteration": "Al-Waahid", "meaning": "The One"},
            {"day_number": 67, "name": "ٱلْأَحَد", "transliteration": "Al-Ahad", "meaning": "The Unique, The Only One"},
            {"day_number": 68, "name": "ٱلصَّمَدُ", "transliteration": "As-Samad", "meaning": "The Eternal, Satisfier of Needs"},
            {"day_number": 69, "name": "ٱلْقَادِرُ", "transliteration": "Al-Qaadir", "meaning": "The Capable, The Powerful"},
            {"day_number": 70, "name": "ٱلْمُقْتَدِرُ", "transliteration": "Al-Muqtadir", "meaning": "The Omnipotent"},
            {"day_number": 71, "name": "ٱلْمُقَدِّمُ", "transliteration": "Al-Muqaddim", "meaning": "The Expediter, The Promoter"},
            {"day_number": 72, "name": "ٱلْمُؤَخِّرُ", "transliteration": "Al-Mu’akhkhir", "meaning": "The Delayer, the Retarder"},
            {"day_number": 73, "name": "ٱلأَوَّلُ", "transliteration": "Al-Awwal", "meaning": "The First"},
            {"day_number": 74, "name": "ٱلْآخِرُ", "transliteration": "Al-Aakhir", "meaning": "The Last"},
            {"day_number": 75, "name": "ٱلْظَّاهِرُ", "transliteration": "Az-Dhaahir", "meaning": "The Manifest"},
            {"day_number": 76, "name": "ٱلْبَاطِنُ", "transliteration": "Al-Baatin", "meaning": "The Hidden One, Knower of the Hidden"},
            {"day_number": 77, "name": "ٱلْوَالِي", "transliteration": "Al-Waali", "meaning": "The Governor, The Patron"},
            {"day_number": 78, "name": "ٱلْمُتَعَالِي", "transliteration": "Al-Muta’ali", "meaning": "The Self Exalted"},
            {"day_number": 79, "name": "ٱلْبَرُّ", "transliteration": "Al-Barr", "meaning": "The Source of Goodness, the Kind Benefactor"},
            {"day_number": 80, "name": "ٱلْتَّوَّابُ", "transliteration": "At-Tawwaab", "meaning": "The Ever-Pardoning, The Relenting"},
            {"day_number": 81, "name": "ٱلْمُنْتَقِمُ", "transliteration": "Al-Muntaqim", "meaning": "The Avenger"},
            {"day_number": 82, "name": "ٱلْعَفُوُّ", "transliteration": "Al-‘Afuww", "meaning": "The Pardoner"},
            {"day_number": 83, "name": "ٱلْرَّؤُفُ", "transliteration": "Ar-Ra’oof", "meaning": "The Most Kind"},
            {"day_number": 84, "name": "مَالِكُ ٱلْمُلْكُ", "transliteration": "Maalik-ul-Mulk", "meaning": "Master of the Kingdom, Owner of the Dominion"},
            {"day_number": 85, "name": "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", "transliteration": "Dhul-Jalaali Wal-Ikraam", "meaning": "Possessor of Glory and Honour, Lord of Majesty and Generosity"},
            {"day_number": 86, "name": "ٱلْمُقْسِطُ", "transliteration": "Al-Muqsit", "meaning": "The Equitable, the Requiter"},
            {"day_number": 87, "name": "ٱلْجَامِعُ", "transliteration": "Al-Jaami’", "meaning": "The Gatherer, the Uniter"},
            {"day_number": 88, "name": "ٱلْغَنيُّ", "transliteration": "Al-Ghaniyy", "meaning": "The Self-Sufficient, The Wealthy"},
            {"day_number": 89, "name": "ٱلْمُغْنِيُّ", "transliteration": "Al-Mughni", "meaning": "The Enricher"},
            {"day_number": 90, "name": "ٱلْمَانِعُ", "transliteration": "Al-Mani’", "meaning": "The Withholder"},
            {"day_number": 91, "name": "ٱلْضَّارُ", "transliteration": "Ad-Dharr", "meaning": "The Distresser"},
            {"day_number": 92, "name": "ٱلْنَّافِعُ", "transliteration": "An-Nafi’", "meaning": "The Propitious, the Benefactor"},
            {"day_number": 93, "name": "ٱلْنُّورُ", "transliteration": "An-Nur", "meaning": "The Light, The Illuminator"},
            {"day_number": 94, "name": "ٱلْهَادِي", "transliteration": "Al-Haadi", "meaning": "The Guide"},
            {"day_number": 95, "name": "ٱلْبَدِيعُ", "transliteration": "Al-Badee’", "meaning": "The Incomparable Originator"},
            {"day_number": 96, "name": "ٱلْبَاقِي", "transliteration": "Al-Baaqi", "meaning": "The Ever-Surviving, The Everlasting"},
            {"day_number": 97, "name": "ٱلْوَارِثُ", "transliteration": "Al-Waarith", "meaning": "The Inheritor, The Heir"},
            {"day_number": 98, "name": "ٱلْرَّشِيدُ", "transliteration": "Ar-Rasheed", "meaning": "The Guide, Infallible Teacher"},
            {"day_number": 99, "name": "ٱلْصَّبُورُ", "transliteration": "As-Saboor", "meaning": "The Forbearing, The Patient"},
        ]

        for name in names:
            NameOfAllah.objects.create(**name)
